### ISSUE TITLE
Registering a factory for a remote loader doesnt work

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [zendframework/zend-mvc-i18n#15]
I want to use a custom remote translation loader.
Sadly there is no documentation on this anywhere on the docs...
I've read the source code and it seems like I could do this:
module.config.php
```php
return [
  'translator' => [
    'remote_translation' => [
        ['type' => MyLoader::class],
    ],
  ],
  'translator_plugins' => [
    'factories' => [
        MyLoader::class => MyLoaderLoaderFactory::class,
    ],
  ],
];
```

However the plugin manager configuration *does nothing*.

Debugging the code reveals that a `TranslatorPluginManager` will be created (with my factory set) in `Zend\I18n\Module->init()` via the ServiceListener.

The factory `Zend\Mvc\I18n\TranslatorFactory` is supposed to give the created PluginManager to the translator instance. But the factory only does that if the (main) DI-Container does not have a registered `Zend\I18n\Translator\TranslatorInterface`. But `Zend\I18n` registers a factory for this key and so a new PluginManager will be created and all my options are forgotten.

**Comment by michalbundyra** [comment]
Fixed in https://github.com/zendframework/zend-i18n/pull/96/files
